# Generated by Django 3.2.16 on 2022-11-20 21:26

from django.db import migrations, models
import users.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('surnames', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='Correo electrónico')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='Móvil')),
                ('hobbies', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Aficiones')),
                ('verified_email', models.BooleanField(blank=True, default=0, verbose_name='Correo_verificado')),
                ('verified_phone', models.BooleanField(blank=True, default=0, verbose_name='Móvil verificado')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
    ]
