# Generated by Django 3.2.16 on 2022-11-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='Correo electrónico'),
        ),
    ]
